### ISSUE TITLE
Question: creating and accessing attributes to gds object

### ISSUE THREAD

**Issue by sariya** [zhengxwen/gdsfmt#23]
Hi, 

Thanks for this data structure. I've difficulty accessing, creating attributes to a gds object.

```
file.gdsdosage<-paste("dosage","_CHR",chr,".gds",sep="")
gdsfile <- createfn.gds(file.gdsdosage)

##pre-existing matrix 
##add them to .gds 
matrix.afr<-as.matrix(df.afr[,-c(1:3)])
matrix.nat<-as.matrix(df.nat[,-c(1:3)])
matrix.ceu<-as.matrix(df.ceu[,-c(1:3)])
add.gdsn(gdsfile , "dosage_eur",matrix.ceu)
add.gdsn(gdsfile , "dosage_nat",matrix.nat)
add.gdsn(gdsfile , "dosage_afr",matrix.afr)

### add SNP ids
add.gdsn(gdsfile,"snp.id" ,df.ceu[,c(1)])
add.gdsn(gdsfile,"snp.position",jointed_rschrpos$POS) ##add position
add.gdsn(gdsfile,"snp.chromosome",chr) ##add CHROMSOME to structure object
closefn.gds(gdsfile)

##subset  for ceu, afr and nat
tempgds <- openfn.gds(file.gdsdosage) ##open

for (anc in  c("nat","afr")){
##iterate using anc variable

I get error for the following loop when accessing elements:

##get dosage -- dosage_afr
  gdsr <- GdsGenotypeReader(tempgds , genotypeVar=paste0("dosage_", anc))
  genoDataList[[anc]] <- GenotypeData(gdsr, scanAnnot=scanAnnot)
}

closefn.gds(file.gdsdosage) ##open

```

I get error as:

> 
> Error in validObject(.Object) :
>   invalid class “GdsGenotypeReader” object: variable snp.chromosome has **incorrect dimension**
> 
> 

Also, I don't know how to get snp.id or chromsome attributes from the object when created.

print(gdsfile, attribute=TRUE) 
this line prints all SNP ids but doesn't print position and chromosome.

Thanks!

**Comment by smgogarten** [comment]
The "invalid class" error comes from the [GWASTools](https://github.com/smgogarten/GWASTools) package. It expects that snp.id, snp.chromosome, and snp.position are all integer vectors of the same length. In your example above, you probably want to do something like

```
add.gdsn(gdsfile,"snp.chromosome",rep(chr, nrow(df.ceu)))
```

You can access data either by using gdsfmt directly, i.e.

```
gds <- openfn.gds(file.gdsdosage)
id <- read.gdsn(index.gdsn(gds, "snp.id"))
chrom <- read.gdsn(index.gdsn(gds, "snp.chromosome"))
```

or by using the GWASTools objects:

```
gds <- GdsGenotypeReader(gds, genotypeVar="dosage_eur")
id <- getSnpID(gds)
chrom <- getChromosome(gds)
```

**Comment by sariya** [comment]
Thank you. :) Appreciate it.
