### ISSUE TITLE
STEAM: Error: is.character(gds.fn) is not TRUE

### ISSUE THREAD

**Issue by sariya** [zhengxwen/gdsfmt#24]
Dear authors,

I'm running error with gdsfmt library, data structure. I'd like to use STEAM library to estimate threshold for local admixture analysis. 
I've opened an issue for this on their repository but I think issue is relevant to this library. Link for issue: https://github.com/kegrinde/STEAM/issues/1

Any help would be appreciated. Thanks.

**Comment by zhengxwen** [comment]
Is `file.gdsdosage` a file name (character)?
`file.gdsdosage` should be a file name, so that you can open this file.
